### ISSUE TITLE
Is this still in use? 

### ISSUE THREAD

**Issue by mjbrender** [basho/riak-ansible#1]
Hey @kellymclaughlin - is this repo still in use? If so, I'd like to move it along with others to Basho Labs as part of our OSS effort. 

If not, let's retire it :+1: 

Thanks!

**Comment by kellymclaughlin** [comment]
Nobody is using afaik. If was one of several failed attempts at automated benchmarking for riak and riak_cs.

**Comment by mjbrender** [comment]
Thanks @kellymclaughlin -- I believe we have some automation work in a different repo these days. I'm planning to retire this one and it's CS peer in favor of what's curated in Labs. More info: https://github.com/basho-labs/the-riak-community/blob/master/config-mgmt-strategy.md

Ping me if you care to dig into the Ansible work going forward - mbrender [at] basho - and thanks for the reply!
